### ISSUE TITLE
ImportError: No module named setuptools_ext

### ISSUE THREAD

**Issue by ghost** [dlapiduz/certbot-s3front#23]
Please help. I am on Debian, and after pip install letsencrypt-s3front I get this

```
Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-I02WKt/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NEr5oh-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-I02WKt/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by rmaddox** [comment]
I just wish to install it on cloudfront. I made it run so far, with the command line like in the README.md but now this:
```
zsh run.zsh 
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt/cli.py", line 26, in <module>
    from acme import jose
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/__init__.py", line 53, in <module>
    from acme.jose.jwa import (
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/jwa.py", line 18, in <module>
    from acme.jose import jwk
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/jwk.py", line 128, in <module>
    class JWKES(JWK):  # pragma: no cover
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/jwk.py", line 137, in JWKES
    ec.EllipticCurvePublicKey, ec.EllipticCurvePrivateKey)
AttributeError: 'module' object has no attribute 'EllipticCurvePublicKey'
```

**Comment by dlapiduz** [comment]
@ghost to be honest I can't reproduce your issue, can you check it again if you are still interested?

Thanks

**Comment by grappler** [comment]
@dlapiduz Ghost is a deleted account, so you will get no response.

**Comment by dlapiduz** [comment]
Thanks @grappler
