### ISSUE TITLE
Rename to certbot-s3front, use certbot package

### ISSUE THREAD

**Issue by emersion** [dlapiduz/certbot-s3front#35]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/simon/projects/aur-certbot-s3front/src/letsencrypt-s3front-0.1.3/letsencrypt_s3front/tests/tls_sni_01_test.py", line 9, in <module>
    from letsencrypt import achallenges
ImportError: No module named letsencrypt
```

**Comment by dlapiduz** [comment]
✔️ It was about time :)
