### ISSUE TITLE
[0.4.0] SyntaxError with python 3.6.6

### ISSUE THREAD

**Issue by elvisangelaccio** [dlapiduz/certbot-s3front#73]
After upgrading to 0.4.0 I get the following stacktrace:

```
2018-07-21 16:01:58,202:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.25.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1297, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 201, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 47, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/certbot_s3front/installer.py", line 140
    cert['ServerCertificateId'] != self.certificate_id:
                                                      ^
SyntaxError: invalid syntax
2018-07-21 16:01:58,202:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by elvisangelaccio** [comment]
Looks like it's just a missing `)` at line 140.
